# Importar

In [2]:
import numpy as np

# Basico

In [3]:
a = np.array([1, 2, 3, 4, 4, 6])
a

array([1, 2, 3, 4, 4, 6])

In [4]:
a[4] = 5
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[:3]

array([1, 2, 3])

In [6]:
# Los arrays son transferibles
b = a[3:]
b
b[0] = 40
a

array([ 1,  2,  3, 40,  5,  6])

In [7]:
# Escribir una matriz
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Dimension, tipo de dato y tamano

In [8]:
a.ndim #dimensiones de a

2

In [9]:
a.shape #3 arreglos con 4 componentes

(3, 4)

In [10]:
a.dtype # Tipo de dato

dtype('int32')

# Arreglos especificos

In [11]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.empty(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.arange(4, 8) #rango

array([4, 5, 6, 7])

In [15]:
np.arange(0, 13, 2) #rango, brinca dos numeros

array([ 0,  2,  4,  6,  8, 10, 12])

In [16]:
np.linspace(0, 10, 5) # rango y divide en partes iguales

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64) #Elegir tipo de dato que quieres
x

array([1, 1], dtype=int64)

# Ordenar

In [18]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [19]:
np.sort(arr) #Arreglo en orden

array([1, 2, 3, 4, 5, 6, 7, 8])

# Concatenar y unir

In [20]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [21]:
np.concatenate((x, y), axis=0) #Concatenar arreglos

array([[1, 2],
       [3, 4],
       [5, 6]])

# Reshape

In [22]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [23]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
c = a.reshape(6,-1) #Reshape
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Agregar dim

In [29]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [34]:
a2 = a[np.newaxis, :] #Agregar dimension a un arreglo
a2

array([[1, 2, 3, 4, 5, 6]])

In [33]:
row_vector = a[np.newaxis, :]
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [39]:
col_vector = a[:, np.newaxis]
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [36]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [37]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [60]:
a = np.array([[1, 2], [2, 3]])
a = a[:, np.newaxis]

a

array([[[1, 2]],

       [[2, 3]]])

# Indexar

In [62]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a[a < 5] #Mneor a 5

array([1, 2, 3, 4])

In [67]:
five_up = (a >= 5) #Mayor a 5
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
c = a[(a > 2) & (a < 11)] #Mayores a dos, menores a 11
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
five_up = (a > 5) | (a == 5) #Mayores a 5 o 5
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
print(five_up) #Booleano, ver que valores cumplen y cuales no

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [93]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
b = np.nonzero(a < 5) #Lugares donde hay valores menores a 5, primer arreglo indice de fila, segundo indice de columna
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [95]:
A = np.array([1, 2, 3, 4]) #Con zip se pueden unir datos con otros, arreglos del mismo tamano
B = np.array([2, 4, 6, 8])

list(zip(A, B))

[(1, 2), (2, 4), (3, 6), (4, 8)]

In [97]:
list_of_coordinates = list(zip(b[0], b[1])) #Coordenadas de donde se encuentra cada valor menor a 5
                                            
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [ ]:
a[b] #Dame los numeros que no son mayores a 5 (los de las coordenadas)

array([1, 2, 3, 4])

# Split y Stack

In [105]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((a1, a2)) #Union vertical de los arreglos

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2)) #Union horizontal de los arreglos

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [109]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3) #Splitear el arreglo en partes iguales pero tomando en cuenta ambas arreglos de las pasada

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [111]:
np.hsplit(x, 4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [ ]:
np.hsplit(x, (3, 5)) #Splitear cortando en partes, del 0:3, 4:5, 6:12

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
b2 = a.copy()
b2 #Para copiar arreglos, ES LA UNICA MANERA DE QUE NO CAMBIE EL ARREGLO ORIGINAL

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Opreaciones de arreglos

In [ ]:
data = np.array([1, 2]) #Sumas
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [ ]:
data - ones #Resta 

array([0, 1])

In [125]:
data * data #Multi

array([1, 4])

In [131]:
(data // data) #Div

array([1, 1])

In [ ]:
a = np.array([1, 2, 3, 4]) #Suma total del arreglo
a.sum()

10

In [ ]:
a = np.array([[1, 7], [2, 6]])
a.sum(axis=0) #Suma vertical

array([ 3, 13])

In [ ]:
a.sum(axis=1) #Suma horizontal

array([8, 8])

In [140]:
data = np.array([1.0, 2.0, 3.0]) #Multiplicar por escalar
data * 1.6

array([1.6, 3.2, 4.8])

In [141]:
print(data.max()) #Maximo
print(data.min()) #Minimo
print(data.sum()) #Suma

3.0
1.0
6.0


In [147]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])