# Importar

In [2]:
import numpy as np

# Basico

In [3]:
a = np.array([1, 2, 3, 4, 4, 6])
a

array([1, 2, 3, 4, 4, 6])

In [4]:
a[4] = 5
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[:3]

array([1, 2, 3])

In [6]:
# Los arrays son transferibles
b = a[3:]
b
b[0] = 40
a

array([ 1,  2,  3, 40,  5,  6])

In [7]:
# Escribir una matriz
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Dimension, tipo de dato y tamano

In [8]:
a.ndim #dimensiones de a

2

In [9]:
a.shape #3 arreglos con 4 componentes

(3, 4)

In [10]:
a.dtype # Tipo de dato

dtype('int32')

# Arreglos especificos

In [11]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.empty(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.arange(4, 8) #rango

array([4, 5, 6, 7])

In [15]:
np.arange(0, 13, 2) #rango, brinca dos numeros

array([ 0,  2,  4,  6,  8, 10, 12])

In [16]:
np.linspace(0, 10, 5) # rango y divide en partes iguales

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64) #Elegir tipo de dato que quieres
x

array([1, 1], dtype=int64)

# Ordenar

In [18]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [19]:
np.sort(arr) #Arreglo en orden

array([1, 2, 3, 4, 5, 6, 7, 8])

# Concatenar y unir

In [20]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [21]:
np.concatenate((x, y), axis=0) #Concatenar arreglos

array([[1, 2],
       [3, 4],
       [5, 6]])

# Reshape

In [22]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [23]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
c = a.reshape(6,-1) #Reshape
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Agregar dim

In [29]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [34]:
a2 = a[np.newaxis, :] #Agregar dimension a un arreglo
a2

array([[1, 2, 3, 4, 5, 6]])

In [33]:
row_vector = a[np.newaxis, :]
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [39]:
col_vector = a[:, np.newaxis]
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [36]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [37]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [60]:
a = np.array([[1, 2], [2, 3]])
a = a[:, np.newaxis]

a

array([[[1, 2]],

       [[2, 3]]])

# Indexar

In [62]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a[a < 5] #Mneor a 5

array([1, 2, 3, 4])

In [67]:
five_up = (a >= 5) #Mayor a 5
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
c = a[(a > 2) & (a < 11)] #Mayores a dos, menores a 11
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
five_up = (a > 5) | (a == 5) #Mayores a 5 o 5
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
print(five_up) #Booleano, ver que valores cumplen y cuales no

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [93]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
b = np.nonzero(a < 5) #Lugares donde hay valores menores a 5, primer arreglo indice de fila, segundo indice de columna
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [95]:
A = np.array([1, 2, 3, 4]) #Con zip se pueden unir datos con otros, arreglos del mismo tamano
B = np.array([2, 4, 6, 8])

list(zip(A, B))

[(1, 2), (2, 4), (3, 6), (4, 8)]

In [97]:
list_of_coordinates = list(zip(b[0], b[1])) #Coordenadas de donde se encuentra cada valor menor a 5
                                            
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [ ]:
a[b] #Dame los numeros que no son mayores a 5 (los de las coordenadas)

array([1, 2, 3, 4])

# Split y Stack

In [105]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((a1, a2)) #Union vertical de los arreglos

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2)) #Union horizontal de los arreglos

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [109]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3) #Splitear el arreglo en partes iguales pero tomando en cuenta ambas arreglos de las pasada

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [111]:
np.hsplit(x, 4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [ ]:
np.hsplit(x, (3, 5)) #Splitear cortando en partes, del 0:3, 4:5, 6:12

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
b2 = a.copy()
b2 #Para copiar arreglos, ES LA UNICA MANERA DE QUE NO CAMBIE EL ARREGLO ORIGINAL

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Opreaciones de arreglos

In [ ]:
data = np.array([1, 2]) #Sumas
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [ ]:
data - ones #Resta 

array([0, 1])

In [125]:
data * data #Multi

array([1, 4])

In [131]:
(data // data) #Div

array([1, 1])

In [ ]:
a = np.array([1, 2, 3, 4]) #Suma total del arreglo
a.sum()

10

In [ ]:
a = np.array([[1, 7], [2, 6]])
a.sum(axis=0) #Suma vertical

array([ 3, 13])

In [ ]:
a.sum(axis=1) #Suma horizontal

array([8, 8])

In [140]:
data = np.array([1.0, 2.0, 3.0]) #Multiplicar por escalar
data * 1.6

array([1.6, 3.2, 4.8])

In [141]:
print(data.max()) #Maximo
print(data.min()) #Minimo
print(data.sum()) #Suma

3.0
1.0
6.0


In [148]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [151]:
a.min(axis=0) #Minimo de cada columna

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [152]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0, 1]#Posicion de matriz

2

In [ ]:
data[1:3]#Agarra fila en posicion 1 y 2

array([[3, 4],
       [5, 6]])

In [ ]:
data[:2, 0]#Filas 0 y 1, columna 0

array([1, 3])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]]) #Si los arreglos no son del mismo tamano, se sumara la matriz mas
ones_row = np.array([1, 1])               #el valor de [1, 1] en los tres subarreglos
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [191]:
print(f'{np.ones((3, 2))}\n') #Puros unos
print(f'{np.zeros((3, 2))}\n') #Puros ceros
rng = np.random.default_rng()  # generar numeros aleatorios
print(rng.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0.68747929 0.93448208]
 [0.12542852 0.25889369]
 [0.78745235 0.42845396]]


# Random numbers

In [238]:
rng.integers(10, size=(2, 4)) #numeros random del 0 al 9

array([[3, 7, 7, 5],
       [9, 9, 0, 0]], dtype=int64)

In [239]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [240]:
unique_values = np.unique(a) #Valores unicos en el arreglo
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [241]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list) #Indices de donde aparecen por primera vez los valores unicos

[ 0  2  3  4  5  6  7 12 13 14]


In [242]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count) #Frecuencia de que tanto aparecen los valores

[3 2 2 2 1 1 1 1 1 1]


In [243]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [244]:
unique_values = np.unique(a_2d)
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [245]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [249]:
unique_rows, index, conteo = np.unique(a_2d, return_index=True, return_counts=True)
print(unique_rows)
print(index)
print(conteo)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[2 2 2 2 1 1 1 1 1 1 1 1]


# Transponer y reshape a matrix

In [259]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose() #Transpuesta 

array([[0, 3],
       [1, 4],
       [2, 5]])

In [261]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr_inv = np.flip(arr) #Empezar del ultimo al inicio (voltear matriz)
arr_inv

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

np.flip(arr_2d) #Matriz volteada de mas dimensiones

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [266]:
np.flip(arr_2d, axis = 0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [267]:
np.flip(arr_2d, axis = 1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [ ]:
arr_2d[1] = np.flip(arr_2d[1]) #Flip la fila en posicion uno
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [ ]:
arr_2d[:, 1] = np.flip(arr_2d[:, 1]) #Flip la columna en posicion 1
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Reshaping and flattening multidimensional arrays

In [270]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x.flatten() #Funcion para hacer tu arreglo 1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a1 = x.flatten() #Flatten no afecta al arreglo original
a1[0] = 99
print(f'{x}\n')  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[99  2  3  4  5  6  7  8  9 10 11 12]


In [276]:
a2 = x.ravel() #Con ravel si afecta el nuevo al original
a2[0] = 98
print(f'{x}\n')  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[98  2  3  4  5  6  7  8  9 10 11 12]


# Mas info

In [280]:
help(max) #Ayuda

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [ ]:
max? #Lo mismo

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a? #Nos dice que es la variable a

Type:        ndarray
String form: [1 2 3 4 5 6]
Length:      6
File:        c:\users\esteb\anaconda3\envs\tsflow\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
   

In [301]:
def double(a):
    '''return a *2'''
    return a*2

In [ ]:
double?

Signature: double(a)
Docstring: return a *2
File:      c:\users\esteb\appdata\local\temp\ipykernel_17280\752383979.py
Type:      function

In [ ]:
double??

Signature: double(a)
Source:   
def double(a):
    '''return a *2'''
    return a*2
File:      c:\users\esteb\appdata\local\temp\ipykernel_17280\752383979.py
Type:      function

# Formulas matematicas

In [ ]:
# Mean Square Error
# error = (1/n) * np.sum(np.square(y_pred-yi))

In [307]:
y_pred = np.array([1, 1, 1])
y_i = np.array([1, 2, 3])

In [308]:
(1/3)*np.sum(np.square(y_pred-y_i))

1.6666666666666665

# Guardar y cargar objetos np

In [311]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
np.save('prueba_1', a) #Guardar arreglo en la misma carpeta

In [ ]:
b = np.load('prueba_1.npy') #Cargar arreglo
b

array([1, 2, 3, 4, 5, 6])

In [315]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.savetxt('prueba_2.csv', csv_arr) #Guardar arreglo como csv

In [ ]:
np.loadtxt('prueba_2.csv') #Cargar arreglo csv

array([1., 2., 3., 4., 5., 6., 7., 8.])

# Importar y exportar CSV

In [318]:
import pandas as pd

# If all of your columns are the same type:
x = pd.read_csv('music.csv', header=0).values
print(x)

FileNotFoundError: [Errno 2] No such file or directory: 'music.csv'

In [ ]:

# You can also simply select the columns you need:
x = pd.read_csv('music.csv', usecols=['Artist', 'Plays']).values
print(x)